OvercastCommunity/CommunityMaps

Wanna Fly/map.xml
- Expanded Ender Portal region.(y:13-14 → 11-14) 
In v1.0.1, some players didn't teleport when they jumped into the portal from a high place.
=> Update Wanna Fly to v1.0.2

Summertime at Brown's Farms/map.xml
You and your teammates will no longer take damage from TNT that you place.
=> Brown's Farms: Disable some types of TNT damage

Zipline/map.xml
- added arrows to kill reward
- removed gapples from spawn kit
- changed spawners to gapple drops (every 10-15 seconds), limit is 1 gapple per spawner
- added arrows to item remove
- removed gapples from item remove
-despite numerous efforts to fix this, people would very occasionally get stuck in the top zip-lines...Unfortunately I have tried all possible methods I could to prevent this but it always happened to 1 odd person every match. Hence I have added a rule to try do this... I was thinking maybe have it kill if the player stays in there for more than 3 seconds but I'd like to hear if that's possible
=> Zipline 1.0.5

Zombie Defense/map.xml
- Removed grief protect (except chest protect)
- Enabled renewables
- Added Shovel and enchanted pickaxe for steves.
=> Update Zombie Defense to v1.0.6

Grand qboid/map.xml
- Added Golden Apples to item remove
- decreased stained glass and wool amounts at spawn and on kill reward
- decreased TNT killreward from 3 kills to 2 kills 
- make the tip that says all hills give out one point each repeat more often.
=> Grand Q*Boid 1.0.1

BlockGlitch/map.xml
This pull request just increases the amount of items in BlockGlitch that would make it more easier to get over walls and a lot less tedious to play the map. Sometimes the item just straight up disappeared and never came back to my inventory lol. This fixes the comment I said in #73 and @StanleyThat approved of these changes
=> Increase spawn items in BlockGlitch

Grand qboid/map.xml
I finally learned how I'm supposed to modify the potion colour, and make something a splash potion.
- Adds damage to jump boost potions so they appear green in game.
- Fixes typo on tip
- Removes "team" from team names
=> Update potion colours in Grand Q-Boid

Zombie Defense/map.xml
- Disabled crafting boat to prevent boat glitch
=> Update Zombie Defense to v1.1.2

Beach Battles/map.xml
- Particles & sounds have been turned off for regenerables
- Build limit quirks with tnt explosions and regerables have been fixed
- Fixed indentation hopefully
- Fixed regions incorrectly bounded
- Inventory has been shuffled to better suit gameplay
- Points increased to 1000 from 750
- Snowball count reduced to 32
- No more tutorial.xml
- Fixed region interferance and "region fighting" for messages 'n' filters
- Fixed quartz blocks getting destroyed in middle islands
- Fixed spawn island and hill letters getting exploded by tnt
- Removed some duplicate and usless blocks from the renew-filters
=> Beach Battles 1.0.1

Ballot Box/map.xml
This PR fixes a bunch of dumb mistakes I made, like leaving in some comments that are no longer needed and forgetting to add arrows in the second part. I have added signs to the filter so players may no longer lose their signs if they accidentally right clicked on them. There is a more complex killreward filter so players will get their coloured stained clay on the first stage and wood on the second stage.
=> Add fix items, killrewards and filters in Ballot Box

Beach Battles/map.xml
- prevented blocks from being placed in spawns
- void region was one block too far for the back of red base allowing for blocks to be freely placed there
=> Beach Battles 1.1.7

Zipline - Moar Gunz Edition/map.xml
- Playerz no longer get blown by their own TNT or other teammatez TNT making it funnier overall
- Playerz no longer take damage from fire_tick (recurring fire damage) only the initial damage countz
- Gun kit is received once leaving spawn
-  Red team changed to the Red Rivalz... sounds better than red gunnerz and I felt red riflez wasn't quite there in termz of pronounciationz
- Can't get stuck @ blue spawn now
Remeber: this is a map for the cool April foolz poolz & also as a /setnext fun map! so don't put in into other poolz very coolz
=> Zipline: Gunz 1.0.2

Space Base/map.xml
- removed protection from woolrooms... people should eb able to kill if they choose
- tnt no longer blows u up
- 64 blocks instead of 48 cause 48 wasn't enough
- removed tips assoicated with woolroom protection
=> Space Base 1.0.11

Fishing Frenzy/map.xml
- Having the rod in the 2nd slot was confusing for players who were used to 2nd slot bows on oc.tc
- Swapped rod slot with bow... (mentioned above)
- added the scorebox gamemode as is was not in xml
- changed it from 750pt limit to an 8min match as it made the most sense to do that
=> Fishing Frenzy 1.0.7

Fishing Frenzy/map.xml
- Wanted to experiment with kills giving less points cause I felt kills giving 5pts (via scoring the fish) was to overpowered
- kill coins created that get given every kill and can be redeemed for 1pt at the scorebox
- kill coins are now kept on death instead of fish which is good cause it gives players a motivation to kill high fish carriers
- fixed small spelling mistakes
=> Update Fishing 1.0.8

dtcm/standard/coreo/map.xml
- broadcast with tips about custom craft has been added.
- added night vision to the starter kits. cookie's team now doesn't have the dark clay's advantage.
- kill rewards give saturation. now cookies won't be a problem.
=> Update Coreo's map.xml

ffa/standard/la_piazza/map.xml
- Since the apple games is over the map's name has been reverted
- Since apple games are now over dev-phase has been removed... this will probabily also be this map's final version
=> La Piazza - Remove apple game name

blitz/standard/gold_in_them_thar_kills/map.xml, ctw/standard/quadrosphere_ctw/map.xml, ctw/standard/stratosphere_ctw/map.xml, dtcm/standard/mushroom_monuments/map.xml, flag/standard/thunderrush/map.xml, mixed/standard/malupa/map.xml, scorebox/halloween/die_noon/map.xml, scorebox/standard/bob-omb_battlefield/map.xml, scorebox/standard/death_denile/map.xml, scorebox/standard/miner_sixty_niner/map.xml, tdm/standard/quadrosphere_rage/map.xml
Creation dates added to a bunch of my maps via <created>, the last few maps that still lack the tag either aren't intended to ever play again at any stage or will have it included with future planned map updates.
Date added to:
- Bob-Omb Battlefield
- Death DeNile
- Die Noon
- Gold in Them Thar Kills
- Malupa
- Miner Sixty Niner
- Mushroom Monuments
- Quadrosphere CTW
- Quadrosphere Rage
- Stratosphere CTW
- Thunderrush
=> Add creation date to most of my maps that are missing it.

ad/tdm/Transit/map.xml
- nerf bomber (slower tnt fuse and reduce speed effect)
- adjust score to half (5 points from scorebox, 1 point from kill)
- fix portal to not teleport observer
- adjust renew rate of stained glass pane
- improve tips and alert
- remove unnecessary lines
=> Transit: v1.1.5

flag/standard/royal_rumble_II/map.xml, flag/standard/the_big_dig/map.xml
From feedback based on mapdev's and my own informed opinion I figured that the name flag runners wasn't too intuitive and did not give the user much of an idea of the game mode being played. I switched it to assault cause it plays similarly to an old halo gamed (thanks halo)
=> Rename flag runners game mode to flag assault

flag/standard/tuscany_hills/map.xml
- Add Projectile Protection I to Chainmail Leggings: This still uses the Actions system for messages, as well as for cases when the player doesn't have the leggings equipped (or they dropped them) - they won't get new ones.
- Modify flag carrying kit: Players now get Slowness I instead of Speed as well as no Knockback Stick/weapon removal.
- Add itemkeep and remove weapons from itemremove (as there's no necessary weapon removal stuff now)
=> Tuscany Hills: v1.0.5

dtcm/standard/deadly_gaze/map.xml
**XML (regions):**
- Fix spawn area boundaries (as players were able to break the carpet and piston blocks due to layout changes)
- Raise no entry area above spawn by 1 block
Found during local testing
=> Deadly Gaze: Fix region boundaries

dtcm/standard/deadly_gaze/map.xml
Makes the skull regions bounded so that they work with the filter as well.
Mostly just so it has better support for weird blocks like some upper halves of slabs that were breakable before
=> Deadly Gaze: Switch to using blocks filter

.github/ISSUE_TEMPLATE/map-update.yaml
Changes the textbox into a different one where it'll let users drag a .zip file to upload
Previously, it was using the smaller box below while other templates were using the larger textarea input.
=> Fix incorrect text box for map update template

dtcm/standard/armature/map.xml
Also reduces drop rates from 10% to 5% for apples
Found during local testing
=> Armature: Fix block drop chances and lower obs spawns

.github/ISSUE_TEMPLATE/contest-submission.yaml, .github/ISSUE_TEMPLATE/map-submission.yaml
Add a checkbox with a link to the submission guidelines to the map submission form.
=> Add map submission guidelines checkbox to forms

flag/standard/the_kings_lava_lair/map.xml
- add leaves to itemkeep to prevent drop on death
- clear inventory to prevent leave duplication
- Leaves added back to kill reward so it's balanced towards spawner play/control & not farming 24 leaves off each player
=> The King's Lava Lair 1.0.3

flag/standard/happy_rainbow/map.xml, tdm/halloween/transit_halloween/map.xml, tdm/standard/transit/map.xml
(sorry for updating it that frequent recently, cuz the redeemable led to many game balancing issues... Orz)
- reduce the amount of arrow in guards' kit & kill reward
- increase the scores of bombers' scorebox
-  remove fall damage
=> Transit v1.2.3 + Happy Rainbow v2.0.1

tdm/halloween/transit_halloween/map.xml, tdm/standard/transit/map.xml
- Reduce scorebox score to 3
- Apply speed II kit when guards inside the train
=> Transit: v1.2.4

tdm/halloween/transit_halloween/map.xml, tdm/standard/transit/map.xml
Redeemable has caused serious game balancing issue since its implementation in v1.2 
and its jump-up-to-score mechanism does not work well. 
It is initially designed to let guards to have an chance to score as bomber did 
and to reduce guards' confusion when they observe a scoring message from bombers. 
Turn out this is not a good solution after various adjustments, 
hopefully seek an alternative approach in later updates. Thanks!
=> Transit: v1.2.5

ctw/standard/prisma_ctw/map.xml
Players were able to open their own wool room chests by breaking the glass and quickly right clicking the chest, this fixes it. Also remove dev phase since map was added to pool.
=> Prisma CTW: Fix wr use filter

ctw/standard/paddos/map.xml
Fix a bug in the previous update where at certain y levels players could interfere with their own wool rooms, because the regions were contracted.
=> Paddo's: fix wool room filters

flag/standard/boar_beach/map.xml
- Use `scoreboard-filter` property to hide flags not in play from objectives scoreboard
- Use `<pulse>...</pulse>` filter to persist message triggers while player remains in required regions
=> Update Boar Beach to version 1.3.1

ctw/standard/curly_pride/map.xml
To prevent filling up player inventories
=> Curly Pride: add stone axe to toolrepair

ctw/standard/greenhill/map.xml
Make the wood in the kill reward the same type of wood as the spawn kit so it can stack
=> Greenhill: Update wood on killreward

arcade/infection/infection_amusement_park/map.xml, arcade/infection/infection_amusement_park_halloween_edition/map.xml
Change requested by the map author: deny usage of some more doors that hiders could close, but seekers were not able to open it again because of the paintings in front of it
=> Amusement Park + Halloween Ed.: deny more doors

flag/standard/crater_resort/map.xml
- TNT damages enemies and self, but not teammates
=> Crater Resort: disable TNT damage for allies

ctw/standard/colorado/map.xml, ctw/standard/gloomwald/map.xml
Noticed the height limits on these maps got increased, this also applies the new limits to the wool room regions.
Also on Colorado fix red's spawn point and disable the rule that prevented players from placing blocks inside the water layers
=> Colorado & Gloomwald: Also apply new height limits to wool room regions

other/bedwars/thunderbird/map.xml
- Fix for Wool not stacking (hopefully)
- Fix for Absorption handing on overlapping Invisibility potions
- Made Emeralds more rare during first 4 minutes
- Tweak on thunder that happens when a team is eliminated
=> Bed Wars: Thunderbird 1.2.0 - Fixes

other/bedwars/thunderbird/map.xml
- Correct the material from glass to stained glass, which resolves glass getting destroyed
- Explain in store that glass probably needs more than 1 layer
- Discount the item by doubling the materials
=> Bed Wars: Thunderbird - 1.3.0 - Glass Fix

dtcm/standard/parabola/map.xml
Fixes `unbreakble` to `unbreakable` to ensure the helmet is unbreakable.
=> Parabola: fix typo

other/bedwars/thunderbird/map.xml
Moved logic which increments armor_level_variable to correct location.   
It was incrementing on death, as the filter for non-ideal action included `<alive>`.
https://github.com/OvercastCommunity/CommunityMaps/issues/803
=> Bed Wars: Thunderbird - Fix Armor Bug

dtcm/standard/rock_the_casbah/map.xml
- Add Double-Jump (for jump pad misfires, etc.)
- Reduce destroyable completion from 100% to 99% (to limit bad final block positioning)
- Reduce non-destroyable period from 100s to 60s
- TNT fuse from 1s to 2s
=> Rock the Casbah - Feedback Updates

other/bedwars/luxor/map.xml, other/bedwars/thunderbird/map.xml
- Remove risky incrementing logic on armor variable 
- Abandon protection values stored in player level variable
- Utilize the already existing team level protection variable instead
- Add new store filters with discrete material and protection variables, instead of the combo variable.
=> Bed Wars: Fix Armor Logic

dtcm/applesmash/map.xml
- Removed block pickup logic that was incorrect, since PGM logic is based on stack amounts and not total inventory
- Downside of this is every pickup eats an inventory slot, so..,
- Added new warning which appears after collecting many enemy blocks which warns player to restack inventory.
- Remove diamond shovels
- Expanded editable area by 4 on each end to facilitate closer sky stairs
=> Apple Smash - 1.1.0 - Updates

arcade/standard/blockglitch_4/map.xml
- Fixed an issue where jumping into the void set the teleportation variables, causing you to be teleported into the ever after after match start, and in the end, kicked from the server for flying.
- Adjusted portal debouncing to help mitigate client-side chunk rendering issues after teleporting at the expense of double teleportation being more visible to the player. In an ideal case, the player would get teleported only once, however, at the current state of PGM, this would bring the map declaration to a total of over 340 portal nodes, making maintaining the map by hand unsustainable in the long-term.
- Fixed an oversight causing the 10th lane to be practically unused for the rest of the match due to it being outside the RNG bounds.
- The initial spawn region has been expanded to the …
=> BlockGlitch 4: v1.1.2

arcade/standard/watch_your_head/map.xml
- Disallows players from spawning in the match after the initial stage has started. This also fixes an issue where the match would lock up at the initial stage if the match wasn't a 1v1 match.
- The respawn message was rewritten to be more appropriate in cases when the player joins midgame.
Ref: #856
=> Watch Your Head: 1.0.1

ctw/standard/wintertime/map.xml
Fixes the issue where a 1 wide region on the middle islands was counted as void
=> Wintertime: expand middle region

ctw/standard/peloponnesia/map.xml
Fixes a couple of problems reported recently:
- Wool room courtyard regions were too large one side, mainly one wool room
- Armor drops removed since kits are upgrade based
=> Peloponnesia: Region Fixes, Item Removes

other/payload/skycastle_islands/map.xml
Add a round of balance changes:
- Lower total map length from 15m to 12m (7m +4m +4m -> 6m +3m +3m)
- Payloads move forwards slightly faster (90s to 70s)
- Payloads move backwards significantly faster (900s to 466s)
- Multiplier for more players on payload significantly lowered (from 10% per player to 5% per player)
- Delay between rounds is slightly higher (12s to 20s)
- Defenders get slightly more arrows as a baseline (8 to 10)
- Added titles after rounds to encourage defenders to fallback and regroup, and to notify attackers of the 20s wait.
- Increasing respawn times for defenders was adjusted to new overall map length (4m,8m,12m to 4m,6m,8m)
Overall these changes should make the payload a bit more volatile (move forwards or backwards quicker).
Note that while lowering overall payload …
=> Skycastle islands 1.1.4

ctw/standard/shroom_galaxy/map.xml
Prevents players from the other team from walking on the edge and jumping into woolroom
=> Shroom Galaxy: Expand spawn regions

dtcm/apple_smash/map.xml
- Logs -> Wood
- Added alive to some filters to prevent PGM leaking sounds to observers that weren't matching filter already
- Added gapple include
- Added simple colors to some broadcasts
- Doubled spawner block drops
- Doubled kill rewards (TNT/blocks), also doubled TNT in store
- Remove staging
=> Apple Smash - Refinements

arcade/standard/bed_rush/map.xml
- No Fall Damage for first 5 seconds of each round for a bridge-mode-like entry, and preventing a mass of rushers from getting knocked into the void as happened during FF2 today
- Health leveled-up to 20 after each round
- Removed some unused spawn protection logic
=> Bed Rush - FF Play Test Updates

arcade/standard/bed_rush/map.xml
Increase player ceiling by 1 to prevent occasional bumping off it
Reduce sound volume for ender dragon growl
Extended fall damage filter slightly, just to be sure
Gapple Kill Reward Include
=> Bed Rush - Minor Adjustments

dtcm/apple_smash/map.xml
- Fix stacking of monument blocks, removing 150~ lines of nutty XML
- Add Team water bucket store option, other store tweaks
- Fixed annoying unremovable block area above build-limit
- Increase monument block spawner rate (for team upgrades)
- Broadcast tweaks
=> Apple Smash - Fix Stacking, Store updates, etc

arcade/standard/bed_rush/map.xml
Add void death include
Add respawn delay 2s
Give player kit when joining at other times than start of game or round
Use initial alert to mention "Round 1" in addition to objective.
=> Bed Rush - Void Death Include, Kit Bug, etc

arcade/standard/bed_rush_anubis/map.xml
- Add void death include
- Add respawn delay 2s
- Raise the ceiling by 1
- Give player kit when joining at other times than start of game or round
=> Bed Rush: Anubis - Play test updates

ctw/standard/fall_of_babylon/map.xml
Pear came on Sunday at request to test map, thanks Pear.  
Game play was too short to evaluate balance of currencies gold & diamonds, but functioned correctly as CTW.
There were some unexpected sounds towards the end of the match.   It is possible there was some conflict with game sounds and the PGM match complete sounds.  Based on this theory some sounds linked to objectives are removed.  Other sounds lowered in volume in response to one player's complaint that those sounds were too loud.
Pear wasn't sure about sign-off to Staging, but I included it here to facilitate testing if possible.  Thanks.
- Reduce volume of thunder for wool seals
- Remove firework twinkle sounds related to objective lamps
- Reduce firework twinkle sound related to team updates
- Staging mode
=> Fall of Babylon - Play test updates

dtcm/apple_smash/map.xml, dtcm/cannonball_cove/map.xml, dtcm/rock_the_casbah/map.xml
These changes utilize the new PGM destroyable `sparks="near"` option (which is in PROD) that I developed with much help from Pablo, which disables the extra sparks sounds for monuments when players are more than 64 blocks away.
This keeps the sounds at a more manageable level and allows observers to "escape" the sounds.
- Apple Smash - going from zzuf updated value of "false" to "near"
- Cannonball Cove - going from "true" to "near"
- Rock the Casbah - going from "true" to "near"
=> Near Sparks - Apple Smash, Cannonball Cove, Rock the Casbah

arcade/standard/bed_rush/map.xml, arcade/standard/bed_rush_anubis/map.xml
Bed Rush: Anubis
- Add bed-breaker's name to end-of-match Alert
- Increase respawn delay to 2.5s
- Replace Redstone/Lapis blocks with Endstone for equality (via block-drops)
- Reduce efficiency of 2 spawned tools by 1
Bed Rush
- Add bed-breaker's name to end-of-match Alert
- Increase respawn delay to 2.5s
=> Bed Rush/Anubis: Add Player Names to Alert, etc

ctw/wrath_of_cthulhu/map.xml
This is a minor attribution edit for Cthulhu and disable of crafting fishing rods for Mish.
This is also a test of submitting an update directly to CommunityMaps/master.
Based on Pear's feedback in mapdev, if this was an edit for which I wanted feedback/confirmation I should leave the PR open with requested review.   Otherwise, I could hit the "Squash and merge" button.
Please let me know if that is correct or anything needs adjustment.  Thanks.
=> Wrath of Cthulhu - Minor Edit

arcade/standard/bed_rush/map.xml, arcade/standard/bed_rush_anubis/map.xml
- Display a "card" in chat that displays the bed breaker
- This allows the final bed breaker to be announced, since big message gets skipped on last
- Use Pablo's new circle alternative score display mode
=> Bed Rush/Anubis - Show Final Bed Breaker

arcade/standard/bow_spleef_shogun/map.xml
Main issue was players ran out of arrows towards end, so implemented Pablo's suggested pulse filter to effectively cool-down the bow to a standard rate, removed the arrow spawner drops.
Secondary issue was frame lag at beginning of match, to help slightly the kit Fireballs reduced to 1, and arrow supply gated.
=> Bow Spleef: Shogun - Play test updates - Pulse

arcade/standard/bow_spleef_shogun/map.xml
- Update to make the game less noisy by removing TNT before they explode,  This doesn't affect game mechanics.
- h/t PeakDominance
=> Bow Spleef: Shogun - Quieter

ctw/notre_daaaaam_of_paris/map.xml
- Removes a stray participating filter and some stray whitespace found in a comment
- Groups the wools back as per the discussion at [1]
- Replaces team filters with direct team references thanks to [2]
Ref: [1] https://discord.com/channels/86514356862320640/172382420954251264/1322340224755302483
Ref: [2] https://github.com/PGMDev/PGM/commit/7070abd3f6b4cb64d6713e3093e36500bc73159f
=> Notre-Daaaaam of Paris: v2.1.3

ctw/mame_i_shrunk_the_pvpers/map.xml
makes sure dying-then-reviving re-applies the team upgrade effects
=> Fix team upgrades not applying to late joiners

dtcm/extraterrestrial/map.xml
- The kill-streak rewards were bugged and have now been adjusted to work as intended
=> Extraterrestrial 1.1.8

dtcm/dominion/map.xml
**This update doesn't contain any gameplay changes**
- fixed a bug where players were unable to destroy blocks that were over void (leaves in this case); discovered by kingbluesapphire
- removed unused filters
- switched to inline enchantments in spawn-kit
- removed attributes that used default values from renewables
- removed blocks that do not appear on the map from itemremove
- used inline filter in the iron block drop rule
- changed chance from 100 to 1 in block drops, because it accepts numbers from 0 to 1, so using higher values doesn't do anything and is confusing
=> Dominion: fix + cleanup

ctw/columbia_ctw/map.xml, ctw/emergency_meeting/map.xml, dtcm/annealing_iii/map.xml, ffa/riot_in_prison_rage/map.xml
While working on https://github.com/OvercastCommunity/CommunityMaps/pull/1023 I identified a few maps where the creation date was some time later than when they were added to the repo. This PR fixes the following four:
Columbia CTW had a creation date of `2021-11-28` added in commit https://github.com/OvercastCommunity/CommunityMaps/commit/772443c5a58ba0fa8e2bc819619f37f3e8097690, but it was loaded on `2021-02-17` in commit https://github.com/overcastCommunity/communityMaps/commit/832dcd37. (~284 day difference)
Emergency Meeting was loaded on `2022-01-07` in commit https://github.com/overcastCommunity/communityMaps/commit/ff656d1a. Commit https://github.com/OvercastCommunity/CommunityMaps/commit/1ec57bcb1cc5c90be14c012c95aa4eca6dba8fc9 added the date `2022-12-21`. (~348 day difference) …
=> Fix creation dates for a few maps

arcade/standard/water_drop_pride_gamer_edition/map.xml
I had a blast dropping a 26 kill streak from the spawn platform, but it sure ruins everyone else's fun. I basically just took my xml from Water Drop: II. The weakness prevents pvp on the top spawn region, and then removes it as soon as the players jump off.
=> Water Drop Pride Gamer Edition: Prevent pvp at spawn platform

ctf/pipes_and_punters/map.xml
- Added a 4-second duration to the resistance effect instead of it defaulting to infinite
- Fixed knockback reduction as its value was set to 0, so players will still be able to take knockback in spawn.
These changes have been tested on a private local testing server to ensure compatibility.
=> Pipes and Punters: Fix Knockback and add duration to Resistance

dtcm/missingno/map.xml
- Reduced the 255 resistance amplifier to 5 as anything beyond that won't have any extra effects.
- Simplified team ID references by directly mentioning the team’s ID, eliminating the need for prior filter definitions.
- Simplified the deny-beacon filter.
- Added water bucket to itemremove
=> MissingNo: 1.1.5

tdm/explosive_vengeance/map.xml
The `<limit>` in the XML is 100 points, which means the match ends at 100 points - however, the objective states that it requires 200. The `<objective>` has been brought down to 100 to reflect this.
=> Explosive Vengeance: Fix objective score discrepancy

ctf/happy_rainbow/map.xml
Contains numerous bug fixes and cleanups:
- ~~The snowball rage variant has been turned into proper rage (duh)~~
- ~~Heavy snowballs are given as a kill reward instead of regular snowballs~~
- ~~Added rage module (this enables melee on snowballs and swords to insta-kill)~~
- I don't know, however, if melee not insta-killing wasn't by any chance intentional. Personally, I like the current state (taking 2-3 hits to kill by melee) a bit more, but it doesn't line up with the expectation of rage being an "insta-kill on hit" gamemode. As such, I'm willing to roll this back if it is intentional.
- Added diamond swords to itemremove
- ~~Removed golden apple kill reward~~
- Team filters have been replaced with direct team references
- ~~Removed explicit gamemode tag, relying on PGM's built-in …
=> Happy Rainbow: 2.0.6

tdm/transit/map.xml
Balancing:
- Bombs moved from kill reward to scorebox reward
- Bombers only score from scorebox
Bug fixes:
- No more kill reward add to inventory after death
- Fixed guards entering the top of scorebox issue
Special thanks to Pablo and Pugzy on the xml!!!
=> Transit 1.2.8 - Scorebox
