OvercastCommunity/CommunityMaps

- Bomber Guys/map.xml
Fixed message grammar by feedback at [previous pull-request](https://github.com/OvercastCommunity/CommunityMaps/pull/25).
> Fixed message grammar (Bomber Guys v1.0.3)

- Anvil/map.xml
- Zipline/map.xml
it took me hours of work but I think I finally fixed the stuck in pipeline glitch for all four top zip-lines! I tested each one 10x to verify it and hopefully when loaded no more issues will occur
> Zipline updated to 1.0.4

- Zipline/map.xml
> Technodono zipline updates

- Anvil/map.xml
> Scorebox = 3pts

- Wanna Fly/map.xml
- Changed kit from bow & arrow to Rage-grenade-snowball
Players can shoot projectiles faster than before. 
- Added jump boost & wall speed boost to observer's kit.
- Added color code to lore message
> Update Wanna Fly to v1.1

- Bomber Guys/map.xml
- Reduced max players (12x4→8x4 for micro) to reduce noisy explosion sounds and lag.
- Little fixed tips
> Update Bomber Guys to v1.0.5

- Zombie Defense/map.xml
- Changed match time (10m→12m)
- Added ladder to all-kit
- Zombies get enchanted diamond sword when they enter to castle
- Steves get infinity & power enchanted bow when they are in castle
- Decreased arrows (32→16)
> Update Zombie Defense to v1.2

- Ballot Box/map.xml
Makes ballot box give out one point instead of three points.
Updates #114
> Decrease scoring on Ballot Box

- Re The End Kingdom/map.xml
> Update Re: The End Kingdom to v1.3.1

- Battlefloat/map.xml
- Added the die kit & portal so that when players fall into the void, they die quickly.
- Changed flag's recover time (→0s) / respawn time(10s→30s) & added slowness effect to flag kit like Long Shot.
- Minor revision of xml
> Update Battlefloat to v2.3.1

- Zombie Defense/map.xml
- Disabled crafting chest/trapped chest
- Added golden apple to itemremove
> Update Zombie Defense to v1.2.1

- Space Base/map.xml
IDK why but I didn't put the speed in a lend kits players could just fly... IF matrix gets mad at my map then I'll re-add is as  a lend kit instead
> Space Base 1.0.5

- Space Base/map.xml
> Space Base 1.0.7

- Royal Rumble/map.xml
Map was very over-crowded so team sizes have been reduced from 15ppl - 8ppl
> Royal Rumble 1.0.8

- Zipline - Moar Gunz Edition/map.xml
- fixed weird spawn stuff with flags & players being able to go in & have resistance... making the match softlock
- bows are useless... have been removed
- lazer does more damage (1hrt -> 2hrts)
> Zipline: Gunz 1.0.1

- Beach Battles/map.xml
Simple spelling fix & fixed intendation
> Beach Battles 1.1.12

- Fishing Frenzy/map.xml
changed swords to stone to try make it a lil harder to kill
> Fishing Frenzy 1.0.2

- Bookshelf x64/map.xml
- Changed team size to 24v24 (for centi)
- Kit (Spawn buff:3s→4s, Added projection protect to chestplate)
> Update Bookshelf x64 to v1.3.2

- Fishing Frenzy/map.xml
- made fish score a little bit less
-  made hill give out slightly more points to help balance things
- made  up by 1 block to try fix the glitchy slab issues
> Fishing Frenzy 1.0.6

- Beehive/map.xml
- change chain helmets to leather helmets
- add blocks kill reward
> Update Beehive to 1.1.6

- Fishing Frenzy/map.xml
- Fish now give different points based on rarity
- apparently you could also get enchanted books so they have a score too!
This is what I think makes the most sense... fishing in a more formal pvp match was never really going to work so it's heading more towards and SNS submission but still keeping it's formal pool status
> Fishing Frenzy 1.0.10

- Zombie Defense/map.xml
- Added custom title
- Changed item name format of Overdrive & Arch
> Update Zombie Defense to v1.2.3

- The Dropper Community Edition/map.xml
> Dropper CE 1.0.3

- The Dropper Community Edition/map.xml
- added back fast regeneration to level 8
- fix bugs in level 13
> Dropper CE 1.0.4

- Keipha CTW/map.xml
- removed wooden bridge
- filled empty chests
- replaced poppies with orchids on the blue teams side
- added map.png
- bumped version number to 1.1.0
> Update Keipha CTW to version 1.1.0

- Factorio Gridbase/map.xml
> Factorio Gridbase 1.3.0

- Old Life CTW/map.xml
- added haste kit for defenders
- lower height limit
- fix region bug
- more wool supplies
- better flying machines
- added wool washing
> Update Old Life CTW to 1.0.1

- Nether War CTW/map.xml
- changed team sizes to 16v16v16v16
> Update Nether War CTW to 1.0.2

- ffa/standard/la_piazza/map.xml
- crossbow shoots arrows slower, hopefully it'll be easier for people to see the projectiles
Note: it's range is still far better than the bow, it's reload speed is slower still
- Fixed a potential exploit which could in theory get people into obs spawn
- legacy colour code characters in item names & lores swapped for more appropriate ones
> La Piazza 1.0.1

- ctw/standard/space_base/map.xml
- Wool-room webs can be broken now
- Fixed build-height bug
- No more food or hunger
> Space base 1.2.3

- ctw/christmas/hotel_at_christmas_eve/map.xml
- ctw/halloween/hotel_at_midnight/map.xml
- ctw/standard/hotel_overcast/map.xml
- you can now flip flip trapdoors and fence gates as normal
> Hotel Overcast + Co. (trapdoors useable)

- tdm/standard/anvil/map.xml
- fall damage is now applied on the map
- players that fall in the poison take fall damage so raindrops are rewarded for drops
- if they survive the fall they die to wither damage
> Anvil 1.2.1

- flag/standard/royal_rumble_II/map.xml
- downgraded iron -> stone
- flag carrier now gets slowness + 7 hearts only to combat how easy it is to score rn with the limited player count
> Royal Rumble II 2.0.2

- flag/standard/royal_rumble_II/map.xml
- Changed the tips & flag carrying messages to make the gamemode more clear
- after this ver may be suitable for pools even?
> Royal Rumble II 1.0.4

- ad/tdm/Transit/map.xml
speed 3 to bomber and speed 2 to guard
shorten tnt explosion time from 1s to 0.7s
push tips to an earlier time
lower instant death region
> Transit 1.0.2 - renamed and buffed attacker

- ad/tdm/Transit/map.xml
reduce arrow in guard kit
lower guard speed effect
> Transit v1.0.3 - Nerf Guard

- ad/tdm/Transit/map.xml
> Transit v1.0.4 - minor changes in tips and deny message

- ad/tdm/Transit/map.xml
> Transit v1.1.2 - Guards can now gain speed from kill

- ctw/standard/happy_rainbow/map.xml
easier to distinguish team blue and observer
remove speed effect better control
more delay on falling block
> Happy Rainbow v1.0.1 - Change team blue color and remove speed effect

- ad/tdm/Transit/map.xml
start with 2 arrows in guard kit
only reward 2 arrows when no arrow left with 2 kill-streak
cannot pickup arrow when u already have one in your inventory
change health boost back to 2 hearts, make tnt kill easier
> Transit v1.1.4 - new kill reward system to guard + fix tnt kill issue

- ctw/standard/happy_rainbow/map.xml
> Happy Rainbow: v1.2.1

- ctw/standard/happy_rainbow/map.xml
- add back string to kill reward
- slightly adjust string spawn rate and tips
- mute glass renewing sound
> Happy Rainbow: v1.2.2

- ctw/standard/happy_rainbow/map.xml
- add knockback resistance when stand on platforms
- remove knockback on sword
- add contribution
- faster death when fall
> Happy Rainbow: v1.2.3

- arcade/hns/hide_n_seek_community/map.xml
I guess there's chests of items? This probably isn't all of them
> Hide n Seek Community: Update itemremove

- flag/standard/kalahari_sanctuary/map.xml
Added Iron boots to item remove (forgot to update that last update)
> Kalahari 1.0.2

- flag/standard/kalahari_sanctuary/map.xml
> Kalahari - Remove Dev Phase

- dtcm/standard/mole_dream/map.xml
Was using wrong values, now uses default ones
> Mole Dream: modify iron regeneration values

- ctw/standard/fairy_tales_metamorphose/map.xml
> Fairy Tales Metamorphose: Kill hunger

- dtcm/standard/salvo_but_its_a_castle_and_theres_2x_monuments/map.xml
Double jump should make it easier to navigate the terrain as it gets blown apart and provide some sort of access to the upper levels.
> Salvo But it's a Castle and There's 2x Monuments: Add double jump

- ctw/standard/geometric_domination/map.xml
- Placing blocks in the ground for tnt & defences should no longer get deleted (thanks @Cazadorian for the report)
- Removed contest timelimit
> Geometric Domination 1.0.6

- tdm/halloween/transit_halloween/map.xml
- tdm/standard/transit/map.xml
- Remove the speed effect from guards' kill reward
> Transit v1.2.2 and Transit Halloween: v1.1.2

- ctw/standard/geometric_domination/map.xml
Add gapples to the woolroom spawners
> Geometric Domination 1.0.10

- scorebox/standard/miner_sixty_niner/map.xml
Title is pretty self-explainatory, make use of structures, countdown bossbars, and the newly introduced pulse filter to heavily simplify the map's functionality
> Update miner sixty niner to use pulse

- arcade/runner/rainbow_race/map.xml
I know this isn't my map and I don't have much of a say, but why is the original author not listed as an author?
Since I'm out of the loop, what did the other authors do to the map other than porting it to java?
> Rainbow Race: Appropriately credit original author

- flag/standard/keeper/map.xml
respawn time from 25 seconds to 13 since both teams get teleported back to spawn when flag is captured!
> flag respawn time from 25 seconds to 13 seconds

- flag/standard/crystal/map.xml
Allow opening a hidden chest with some gear
> Crystal: allow opening chests

- arcade/standard/blockglitch_3/map.xml
Based on feedback after testing
> BlockGlitch 3: increase size of checkpoints

- flag/standard/crater_resort/map.xml
- Remove the wither poison death
- Auto-tp players into the void once they touch the death-glass layer
- Tp spectators to the surface if their team carries the flag
- Increase arrows in spawn-kit
> Crater Resort v1.0.2

- ctw/standard/peloponnesia/map.xml
- Fixed emerald spawner areas not being protected
- Fixed breakable woolroom chests
- Tuned some regions
> Peloponnesia 1.1.0 - Fixes

- ctw/standard/peloponnesia/map.xml
- Add sound to team upgrades messages
- Increase gapple spawner rate based on feedback from byRobo
> Peloponnesia - 1.2.0 - Updates

- other/bedwars/thunderbird/map.xml
Add Fireball Power update to match Luxor.
> Bed Wars: Thunderbird - Fireball Update

- ctw/standard/fairy_tales_metamorphose/map.xml
Should fix issues with lava not flowing (https://media.discordapp.net/attachments/172382420954251264/1073100606639722506/2023-02-08_20.36.02.png?width=832&height=468)
Also this is a sick include, thanks @zzufx!
> Fairy Tales Metamorphose: Use deny lava include

- ctw/standard/peloponnesia/map.xml
Remove plain apple from kit, and slot references for gapple/bucket
Update kit logic for gapple and water bucket upgrades to not depend on slots
> Peloponesia - Fix Gapple stomping inventory

- ctw/standard/black_betty/map.xml
> Black Betty - Warnings

- other/bedwars/luxor/map.xml
- other/bedwars/thunderbird/map.xml
- Tone down world border damage
> Bedwars - Luxor/Thunderbird - World Border nerf

- ctw/standard/geometric_domination/map.xml
This is thanks to a suggestion by JustTNT.
It should make it a lot easier to build TNT cannons without running out of blocks
> Add extra building blocks - Geometric Domination

- arcade/standard/the_grand_dueling_tournament_ii/map.xml
Making a pr since I don't have write access to the repo
Swap out parentheses in the grand dueling tournament II with underscores.
For https://github.com/PGMDev/PGM/pull/1257
> Update grand dueling tournament II to not use parentheses

- arcade/standard/the_grand_dueling_tournament_ii/map.xml
- Fixes incorrect defeat announcements at the end of a round
- Fixes inter-arena portals in round 3 sometimes not working
- Fixes observers being teleported to spectator zone after an arena finishes
- Combines the `kit-announcer` and `kit-applicator` actions into a single action for better maintainability
- Adds missing UHC kit
- Increases default team capacity to 6
> Update Grand Dueling Tournament II to v2.0.3

- arcade/standard/the_grand_dueling_tournament_ii/map.xml
- Another fix to inter-arena sectator teleporting - sometimes you were teleported to an area which had already ended after the one you were spectating ended
- Swaps UHC health potions with golden apples
> Update The Grand Dueling Tournament II to version 2.1.1

- arcade/standard/blockglitch_4/map.xml
Instead of broadcasting a subtle tip at the beginning that is hard to notice, players eligible to be teleported will be presented with a message saying they'll be teleported when they fail.
Ref: #836
> BlockGlitch 4: v1.1.1

- arcade/standard/the_grand_dueling_tournament_ii/map.xml
- Fixes players that join between rounds being sent to arena spectator zone and missing out on that round
- Increases snow renewal interval on Spleefing Tournament
- Spleefing Tournament sudden death countdown is scoped to match and now displays a message in chat
- Simplifies some filters
> The Grand Dueling Tournament II: v2.1.2

- arcade/standard/hide_n_seek/map.xml
- Increases frequency of house removals, but less houses removed each trigger
- Changes 3 frame house removal flash to just 1
- Fixes Seekers not receiving correct kit after respawn
> Hide n' Seek: v2.1.1

- dtcm/applesmash/map.xml
- Removed the intro melody
- Removed the team upgrade melody
- Removed the pickup enemy block first time melody
- Removed the pickup self block first time melody
- Removed team upgrade sounds that were customized to the purchased item and replaced with more generic sounds
> Apple Smash - Remove Music

- arcade/standard/blockglitch_4/map.xml
- Reworked the teleportation system to feel less like a hack and to be more logical and predictable.
- Respawn potions are not taken away at checkpoints anymore. 
Ref: #836
> BlockGlitch 4: v1.1.3

- ffa/jurassic_attack_ffa/map.xml
- ffa/jurassic_attack_rage/map.xml
Resolves https://www.youtube.com/watch?v=cA0ZDCl6AVI where the player kills newly spawned players on repeat. Added spawn resistance to non rage counterpart as well
> Add spawn resistance to Jurassic Attack FFA/RAGE

- arcade/standard/hide_n_seek/map.xml
Hiders have compass that shows them the nearest seeker to their location
> Hide n Seek: Add seeker tracking compass

- arcade/standard/bed_rush/map.xml
- Fixed observer kits, cause that got missed in the rewrite
- Fixed timelime
- Refined broadcasts
> Bed Rush - fixed observer kits again, fixed time limit, refine broadcasts

- ctw/standard/hotel_overcast/map.xml
Added the diamond axes and spades to itemrepair
> Hotel Overcast Hotfix

- dtcm/apple_smash/map.xml
Store Item - Personal "God Apple" reduced from 3 to 1
Store Item - Team Shears add Efficiency
Store Item - Team Helmet price reduced
Other minor changes to sounds, broadcasts, filters
> Apple Smash - Refinements

- arcade/standard/bed_rush_anubis/map.xml
Add Shears for Team Tool Spawner
Extend maximum time limit to 20m
Reduce sound volume for ender dragon growl
Extended fall damage filter slightly, just to be sure
Gapple Kill Reward Include
Staging Phase (Zzuf signed-off)
> Bed Rush: Anubis - Minor Adjustments

- blitz/cannonquest/map.xml
quick fix to speed up gameplay until i properly update the map
- time limit 15m -> 8m
- mid opens up 5m -> 3m
- border shrink start 10m -> 5m
- border shrink duration 4m -> 2m
- fixed iron helmet durability
> CannonQuest 1.0.3

- dtcm/rock_the_casbah/map.xml
- Protect the TNT under TNT spawner with placement deny region
- Remove staging mode
> Rock the Casbah - Protect Spawner TNT

- ctw/fall_of_babylon/map.xml
- Fix spawn protect regions - h/t Frap
- Boost gold drops for a few blocks
- Fix spelling of Bazaar
- Lower price of Protection I
> Fall of Babylon: Region updates, etc

- ctw/fall_of_babylon/map.xml
- No updates needed from play test
- Prod phase
> Fall of Babylon - Prod phase

- dtcm/cytokinesis/map.xml
Wasn't able to recreate the missing pickaxe bug in my testing, but have made logic updates to move away from replacing old items with "air" as it seems that the subsequent kit force may not be working due to lack of slot specified.
But also, don't want to tie it to a specific slot, so just replacing old items with new items directly.
> Cytokinesis - Test test updates

- ctw/fall_of_babylon/map.xml
- dtcm/cytokinesis/map.xml
Fall of Babylon
- Fixed incorrect block material and data for store upgrade icon and kit blocks
Cytokinesis
- Dev Phase
> Fall of Babylon - Fix Block Setup, Cytokinesis - Dev Phase

- dtcm/cytokinesis/map.xml
- Boost Pickaxes by 2 levels
- Actions to replace "dropped" pickaxes
- Mining Fatigue trap costs more
> Cytokinesis - Boost Pickaxe Strength, etc

- dtcm/cytokinesis/map.xml
- Scale back the default pickaxe and first two store upgrades
- Store price tweaks
> Cytokinesis - Further Pickaxe Adjustments

- ctw/peloponnesia/map.xml
Error message added for iron area
> Peloponnesia - Fix blank error message

- arcade/standard/bow_spleef_shogun/map.xml
- Raised void death to 120 due to maps high playing y level
> Bow Spleef Shogun: Improvements

- dtcm/cytokinesis/map.xml
Boost spawn rate of main store currency when smaller match.
> Cytokinesis - Small Match Spawner Boost

- dtcm/cytokinesis/map.xml
- Bumped team size to 24v24
- Lowered price of some items, including first 3 pickaxe upgrades
- Faster center glowstone spawner
- Removed staging mode
> Cytokinesis - Minor Adjustments

- dtcm/dynamite/map.xml
Fixed playable region for Dynamite, removed leftover quotes.
> Dynamite: Fix map.xml

- ctf/tom_brady/map.xml
- Turn off the flag-post fire slightly before flag appears
- For throws and catches, retrigger flag-post fire to avoid playtest glitch
- Augment the catch sounds
> Tom Brady - Minor Adjustments

- ctf/tom_brady/map.xml
- XML Clean-up
- Use sound define missing in 1 spot
- Minor tweaks to catch sounds
> Tom Brady - Clean-up

- ctf/tom_brady/map.xml
> Tom Brady - Fix

- ctf/tom_brady/map.xml
> Tom Brady: Prod Phase

- ctf/tom_brady/map.xml
- Added constants for game/player states
- Rename some variables, etc
- Item remove additions
- Minor updates for messages (flag vs football)
> Tom Brady - XML Improvements

- ctf/the_blizzard_bowl/map.xml
- ctf/tom_brady/map.xml
- Thanks for the bug report Tommy, et all
- Fixes bug where killing scorer from last round resulted in picking up the flag
> Brady/Blizzard - Bugfix

- ctf/tom_brady/map.xml
- Name replacements for throw, catch, etc
- Kill reward adjustment
> Tom Brady - Player Names on Events

- ctf/the_overcast_bowl/map.xml
- ctf/tom_brady/map.xml
- TB: Fixed Stripped wrong player bug
- Overcast: Removed Quarters
- General consistency
> Tom Brady - Bugfix, Overcast Bowl - Remove Quarters

- ctf/shingeki_no_brady/map.xml
- Reduce glitch lock potential by tightening up the scoring regions
> Shingeki no Brady - Fix Region

- dtcm/dynamite/map.xml
Add missing filter that was preventing the map from loading (sorry elim)
> Dynamite 1.2.5

- touchdown/pigskin_punchout/map.xml
Community voted for Sharpness III on Piggy Puncher melee weapon
> Pigskin Punchout - Sharper Punchers

- touchdown/pigskin_punchout/map.xml
- Change slowness pot to speed II
- Goal region adjustments
- Kill rewards - add sharpness
> Pigskin Punchout - Refinements

- arcade/infection/infection_skull_island/map.xml
- Make it easier for Humans by increasing final border size
- Buff Infected while in cage to prevent premature death
> Infection: Skull Island - Balance & Buff
